language: ruby
rvm:
- 2.6.5

branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config

script:
- gem update --system
- gem install jekyll
- bundle install
- bundle exec jekyll build

after_success:
- ssh root@47.102.222.59 "cd ~/blog && git pull origin dev:dev && jekyll bundler"

addons:
  ssh_known_hosts: 47.102.222.59
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
