language: ruby
rvm:
- 2.22
- jruby
addons:
  ssh_known_hosts: blog.finalcore.cn
before_install:
- openssl aes-256-cbc -K $encrypted_435f27f33ba6_key -iv $encrypted_435f27f33ba6_iv
  -in id_ras_deploy.enc -out ~/.ssh/id_ras_deploy -d

script:
- bundle install
- bundle exec jekyll build

after_success:
- git pull origin dev

branches:
 only:
  - dev

env:
 global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
