language: ruby
rvm:
- 2.7

# safelist
branches:
  only:
  - dev

before_install:
- openssl aes-256-cbc -K $encrypted_435f27f33ba6_key -iv $encrypted_435f27f33ba6_iv
  -in id_ras_deploy.enc -out ~/.ssh/id_ras_deploy -d
deploy:
- cd /root/Blog
- touch test.text

env:
 global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
