branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.102.222.59\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 
addons:
  ssh_known_hosts:
  - 47.102.222.59
